### ISSUE TITLE
Fix bugs

### ISSUE THREAD

**Issue by SimonasTr** [crnd-inc/crnd-web#1]
Great idea, especially for version11.

Several bugs:
In cases where records are editable in tree view, pop up 

- In cases where records are editable in tree view, pop up 
- if text is long, pop up fails to correctly appear

![image](https://user-images.githubusercontent.com/45077736/62348584-c66ce500-b505-11e9-8172-d4dbe1e42e35.png)

**Comment by katyukha** [comment]
Thanks for this bug-report)

We are working on this.

**Comment by EgorSummer** [comment]
Thanks for this bug-report!

Fixed and slightly expanded.

**Comment by SimonasTr** [comment]
Great! I really like the idea. Version 11 with it's menu on the left has a big problem with tree views which are in sheet forms.

I thought of  alternative solutions:
1.  sheet width can we expanded (already adjusted it a bit)
2. Other idea I come up with is as follows.
    By default sheet is aligned in the middle of the page (ignoring left menu). If we move the sheet to the very left (right next to the left menu), a lot of unused area frees up on the right which could be used for additional info .
E. g. 
- hovering on the list record makes a pop-up which could contain a record info which is defined in it's form view.
- other might be harder to code. Currently if record is not editable in the tree view, record click in tree view opens up a separate wizard which causes to lose access to the parent form. Placing that wizard in the area on the right seems would be amazing

Thanks for the fixes.
