### ISSUE TITLE
Html field support

### ISSUE THREAD

**Issue by SimonasTr** [crnd-inc/crnd-web#2]
In e. g.  project task we have a html field description. If we put it into tree view, the height of every list line becomes very high where your extension would come into play really nicely. However, it renders all html tags.

Also, such fields as description will probably take more text, so parameters to set the popup box size would be nice.
![image](https://user-images.githubusercontent.com/45077736/62457949-7b143a00-b784-11e9-8b59-f0fcdd7054c4.png)

**Comment by katyukha** [comment]
Hello,

Thanks for this issue)

We will check it and try to fix it, when we have time.

Also i have a question: is it good idea to show in tree view large pieces of text?
In our helpdesk we use one more computed field to show only small piece of text converted from html to normal text (via [html2text](https://pypi.org/project/html2text/)). But, event small piece of text has different height for each record, thus we have created this widget.

**Comment by SimonasTr** [comment]
Well, it is probably not. However in some cases I would find it very convenient to have such preview both in list and in kanban views as it would save a lot of loading and field computing.

**Comment by katyukha** [comment]
Hi @SimonasTr 

We have updated version of this module for 11.0 branch. Please, check it and tell us if it fits your needs.

Now, there is 3 widgets instead one:
- dynamic_popover_char
- dynamic_popover_text
- dynamic_popover_html

For more info - read docs: https://github.com/crnd-inc/crnd-web/tree/11.0/crnd_web_list_popover_widget

**Comment by katyukha** [comment]
This issue seems to be solved, closing
